#!/usr/bin/env php
<?php // -*-php-*-
if ($argv[1] == "out") {
    shell_exec ("("
                ."cd ~/bin;"
                ."rm -rf keyout.tgz;"
                ."gpg -d  keyout.tgz.gpg >keyout.tgz;"
                ."tar -xzkf keyout.tgz;"
                ."rm -rf keyout.tgz;"
                .")");
}
else  {
    shell_exec ("("
                ."cd ~/bin;"
                ."tar -czf keyout.tgz dot/.ssh dot/.gnupg;"
                ."gpg -c  keyout.tgz;"
                ."rm -rf keyout.tgz;"
                .")");
}
?>